using System.Windows;
using System.Windows.Controls;
using System.Windows.Markup;

namespace BioCentri.App.Components.Feedback;

/// <summary>
/// Centred hero card for pages without content yet. Reusable across every
/// feature page so the visual treatment is uniform. The page author's
/// "this is what M2 looks like" baseline.
/// </summary>
[ContentProperty(nameof(Content))]
public partial class EmptyState : Border
{
    public static readonly DependencyProperty TitleProperty =
        DependencyProperty.Register(
            nameof(Title), typeof(string), typeof(EmptyState),
            new PropertyMetadata("Nothing here yet", OnTitleChanged));

    public static readonly DependencyProperty SubtitleProperty =
        DependencyProperty.Register(
            nameof(Subtitle), typeof(string), typeof(EmptyState),
            new PropertyMetadata("Once a feature ships, its capability will show up here.", OnSubtitleChanged));

    public static readonly DependencyProperty IconKeyProperty =
        DependencyProperty.Register(
            nameof(IconKey), typeof(string), typeof(EmptyState),
            new PropertyMetadata("Icons.Status.Info", OnIconKeyChanged));

    public string Title
    {
        get => (string)GetValue(TitleProperty);
        set => SetValue(TitleProperty, value);
    }

    public string Subtitle
    {
        get => (string)GetValue(SubtitleProperty);
        set => SetValue(SubtitleProperty, value);
    }

    public string IconKey
    {
        get => (string)GetValue(IconKeyProperty);
        set => SetValue(IconKeyProperty, value);
    }

    /// <summary>Optional primary action (e.g. "Add App"). Child XAML elements
    /// placed inside the <c>&lt;EmptyState&gt;</c> tag land here.</summary>
    public object? Content
    {
        get => Actions.Content;
        set => Actions.Content = value;
    }

    // `Actions` is auto-generated by InitializeComponent from
    // x:Name="Actions" in EmptyState.xaml. We use it directly so the
    // public surface stays as just the `Content` property (the standard
    // ContentControl pattern).


    public EmptyState()
    {
        InitializeComponent();
    }

    private static void OnTitleChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
    {
        if (d is EmptyState s && s.TitleText is { } t) t.Text = (string)e.NewValue;
    }

    private static void OnSubtitleChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
    {
        if (d is EmptyState s && s.SubtitleText is { } t) t.Text = (string)e.NewValue;
    }

    private static void OnIconKeyChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
    {
        if (d is EmptyState s && s.LeadingIcon is { } icon) icon.GeometryKey = (string)e.NewValue;
    }
}
